services:
  application:
    container_name: app
    build:
      dockerfile: /Dockerfile
    ports:
      - 8080:8080
      - 8085:8085
    depends_on:
      - mongodb
      - minio
      - postgres
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SERVER_PORT=8080
      - SOCKETSERVER_HOST=application
      - SOCKETSERVER_PORT=8085
      - SPRING_DATASOURCE_POSTGRES_URL=jdbc:postgresql://postgres:5432/auth
      - SPRING_DATASOURCE_POSTGRES_USERNAME=postgres
      - SPRING_DATASOURCE_POSTGRES_PASSWORD=password
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=auth
      - SPRING_DATA_MONGODB_USERNAME=mongo
      - SPRING_DATA_MONGODB_PASSWORD=password
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_MAIL_USERNAME=hosniboun@gmail.com
      - TWILIO_ACCOUNT_SID=AC3f09f0f73c640e9f03e98e6d4f3ae0fd
      - TWILIO_AUTH_TOKEN=1af7c3af4ab4c81344abd9126fc04801
      - TWILIO_PHONE_NUMBER=213666479862
      - TWILIO_SERVICE_SID=VA2ef474cf2ad41c01b9fba2249a7ca7ff
      - MINIO_URL=http://minio:9000
      - MINIO_BUCKET=spring-profile-bucket
      - MINIO_ACCESSKEY=lbwq4WPyg69EBuRh
      - MINIO_SECRETKEY=wxMYVsGCzINFjTeRLI7J7owyfaI7xYK1
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - minio:/data
    environment:
        MINIO_ROOT_USER: minio
        MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9090"
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://mongo:password@mongo_db:27017/
volumes:
  postgres: {}
  redis: {}
  mongo: {}
  minio: {}
