services:
  application:
    container_name: app
    build:
      dockerfile: /Dockerfile
    ports:
      - 8080:8080
      - 8085:8085
    depends_on:
      - mongodb
      - minio
      - postgres
      - redis
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - minio:/data
    command: server /data --console-address ":9090"
  postgres:
    profiles:
      - dev
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/data
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongodb
    ports:
      - 8081:8081
volumes:
  postgres: {}
  redis: {}
  mongo: {}
  minio: {}
