server:
    port: 8080
    error:
        include-message: always
socket-server:
    host: 127.0.0.1
    port: 8085
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: ${SPRING_DATASOURCE_POSTGRES_URL:jdbc:postgresql://localhost:5432/auth}
        username: ${SPRING_DATASOURCE_POSTGRES_USERNAME:postgres}
        password: ${SPRING_DATASOURCE_POSTGRES_PASSWORD:password}
    data:
        mongodb:
            authentication-database: admin
            auto-index-creation: true
            database: auth
            host: localhost
            password: password
            port: 27017
            username: mongo
        redis:
            host: localhost
            port: 6379
    flyway:
        baseline-description: init
        baseline-on-migrate: true
        baseline-version: 1
        enabled: true
        user: ${SPRING_DATASOURCE_POSTGRES_USERNAME:postgres}
        password: ${SPRING_DATASOURCE_POSTGRES_PASSWORD:password}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
    mail:
        host: smtp.gmail.com
        password: rnwdfsagqpdggwik
        port: 465
        properties:
            mail:
                smtps:
                    auth: true
                    ssl:
                        checkserveridentity: true
                        trust: smtp.gmail.com
                    starttls:
                        enable: true
        protocol: smtps
        username: hosniboun@gmail.com
minio:
    accessKey: lbwq4WPyg69EBuRh
    bucket: spring-profile-bucket
    secretKey: wxMYVsGCzINFjTeRLI7J7owyfaI7xYK1
    url: http://localhost:9000
twilio:
    account:
        sid: AC3f09f0f73c640e9f03e98e6d4f3ae0fd
    auth:
        token: 1af7c3af4ab4c81344abd9126fc04801
    phone:
        number: 213666479862
    service:
        sid: VA2ef474cf2ad41c01b9fba2249a7ca7ff
