spring:
    profiles:
        active: local
    main:
        web-application-type: servlet
    mvc:
        static-path-pattern: /site/**
    servlet:
        multipart:
            max-file-size: 5MB
apiPrefix: /api/v1
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html
file:
    upload:
        max-size: 1048576
