apiPrefix: /api/v1
server:
    port: ${SERVER_PORT:8080}
    error:
        include-message: always
socket-server:
    host: ${SOCKET_SERVER_HOST:127.0.0.1}
    port: ${SOCKET_SERVER_PORT:8085}
file:
    upload:
        max-size: 1048576
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: ${SPRING_DATASOURCE_POSTGRES_URL:jdbc:postgresql://localhost:5432/auth}
        username: ${SPRING_DATASOURCE_POSTGRES_USERNAME:postgres}
        password: ${SPRING_DATASOURCE_POSTGRES_PASSWORD:password}
    data:
        mongodb:
            authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATIONDATABASE:admin}
            auto-index-creation: ${SPRING_DATA_MONGODB_AUTOINDEXCREATION:true}
            database: ${SPRING_DATA_MONGODB_DATABASE:auth}
            host: ${SPRING_DATA_MONGODB_HOST:localhost}
            password: ${SPRING_DATA_MONGODB_PASSWORD:password}
            port: ${SPRING_DATA_MONGODB_PORT:27017}
            username: ${SPRING_DATA_MONGODB_USERNAME:mongo}
        redis:
            host: ${SPRING_DATA_REDIS_HOST:localhost}
            port: ${SPRING_DATA_REDIS_PORT:6379}
    flyway:
        baseline-description: init
        baseline-on-migrate: true
        baseline-version: 1
        enabled: true
        user: ${SPRING_DATASOURCE_POSTGRES_USERNAME:postgres}
        password: ${SPRING_DATASOURCE_POSTGRES_PASSWORD:password}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
    mail:
        host: smtp.gmail.com
        password: ${SPRING_MAIL_PASSWORD:rnwdfsagqpdggwik}
        port: 465
        properties:
            mail:
                smtps:
                    auth: true
                    ssl:
                        checkserveridentity: true
                        trust: smtp.gmail.com
                    starttls:
                        enable: true
        protocol: smtps
        username: ${SPRING_MAIL_USERNAME:hosniboun@gmail.com}
    main:
        web-application-type: servlet
    mvc:
        static-path-pattern: /site/**
    servlet:
        multipart:
            max-file-size: 5MB
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html
minio:
    accessKey: ${MINIO_ACCESSKEY:lbwq4WPyg69EBuRh}
    bucket: ${MINIO_BUCKET:spring-profile-bucket}
    secretKey: ${MINIO_SECRETKEY:wxMYVsGCzINFjTeRLI7J7owyfaI7xYK1}
    url: ${MINIO_URL:http://localhost:9000}
twilio:
    account:
        sid: ${TWILIO_ACCOUNT_SID:AC3f09f0f73c640e9f03e98e6d4f3ae0fd}
    auth:
        token: ${TWILIO_AUTH_TOKEN:1af7c3af4ab4c81344abd9126fc04801}
    phone:
        number: ${TWILIO_PHONE_NUMBER:213666479862}
    service:
        sid: ${TWILIO_SERVICE_SID:VA2ef474cf2ad41c01b9fba2249a7ca7ff}
