server:
    port: 8080
    error:
        include-message: always
socket-server:
    host: 127.0.0.1
    port: 8085
spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:testdb
        username: sa
        password:
    data:
        mongodb:
            authentication-database: admin
            auto-index-creation: true
            host: localhost
            port: 27017
            database: auth
            username: mongo
            password: password
        redis:
            host: localhost
            port: 6379
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                format_sql: true
        show-sql: true
    flyway:
        enabled: false
    h2:
        console:
            enabled: true
            settings:
                web-allow-others: true
    mail:
        host: smtp.gmail.com
        password: rnwdfsagqpdggwik
        port: 465
        properties:
            mail:
                smtps:
                    auth: true
                    ssl:
                        checkserveridentity: true
                        trust: smtp.gmail.com
                    starttls:
                        enable: true
        protocol: smtps
        username: hosniboun@gmail.com
minio:
    accessKey: I6qgqsiYOmOtsRUj
    bucket: spring-profile-bucket
    secretKey: vB3MqoG1e3gXWWLUxrf8IPYVzp56RQBW
    url: http://localhost:9000
twilio:
    account:
        sid: AC3f09f0f73c640e9f03e98e6d4f3ae0fd
    auth:
        token: 1af7c3af4ab4c81344abd9126fc04801
    phone:
        number: 213666479862
    service:
        sid: VA2ef474cf2ad41c01b9fba2249a7ca7ff
jwt:
    access:
        key: 2B4B6250655368566D597133743677397A244226452948404D635166546A576E
        duration: 2
    refresh:
        key: 3272357538782F413F4428472B4B6250655368566D5970337336763979244226
        duration: 1440

